CavQuest/urls.py
from django.contrib import admin
from django.urls import include,path
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from CavQuest_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name='index'),
    path('homepage_loggedin', views.homepage_loggedin, name='homepage_loggedin'),
    path('', include('CavQuest_app.urls', namespace='CavQuest_app')),
    path('accounts/', include('allauth.urls'),name="social"),
    path('logout/', LogoutView.as_view(next_page=''), name='logout'),
    path('successful_submission/', views.successful_submission, name='successful_submission'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/CavQuest_app/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load socialaccount %}
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'CavQuest_app/about.css' %}">
  <link rel="stylesheet" href="{% static 'CavQuest_app/navbar.css' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <title>About Us!</title>
</head>
<body>
<ul class = "menu">
  <li><a class="active" href="{% url 'homepage_loggedin' %}">Home</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:user_profile' %}"> Profile</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:tutorial' %}"> Tutorial</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:about' %}"> About</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:logout_view' %}"> Logout</a></li>
</ul>
  <div class="wrapper">
    <div class="page-header page-header-small">
      <div class="page-header-image" data-parallax="true" style="background-image: url('https://conferences.virginia.edu/sites/conference.virginia.edu/files/Parking.jpg');">
      </div>
      <div class="content-center">
       <div class="container">
  <img src="https://conferences.virginia.edu/sites/conference.virginia.edu/files/Parking.jpg" alt="about_us"
       style=" object-fit: cover; width:100%; height:200px; opacity:0.65;">

  <div class="about_us" style="font-size:75px; color:#101757;">About Us!</div>
</div>
      </div>
    </div>
    <div class="section section-about-us">
      <div class="container">
        <div class="row">
          <br>
        </div>
        <div class="separator separator-primary"></div>
        <div class="section-story-overview">
          <div class="row">
            <div class="col-md-6">
              <div class="image-container image-left" style="background-image: url('https://raw.githack.com/creativetimofficial/now-ui-kit/master/assets/img/login.jpg')">
                <!-- First image on the left side -->
                <p class="blockquote blockquote-primary">This project was created by UVA CS 3240 students Nicole Savage,
            Maria Rahmouni, Zhennguang Wang, Rushvi Patel, and Sunny Chanda.
                  <br>
                  <br>

                </p>
              </div>
              <!-- Second image on the left side of the article -->
               <img src="https://lightandshadowsphotography.files.wordpress.com/2014/08/uva-rice-hall.jpg" alt="about_us" style=" object-fit: cover; width:100%; height:300px; ">
            </div>
            <div class="col-md-5">
              <!-- First image on the right side, above the article -->
              <div class="image-container image-right" style="background-image: url('https://lightandshadowsphotography.files.wordpress.com/2014/08/uva-rice-hall.jpg')"></div>
              <h3>Inspiration </h3>
             <p>Before beginning this project, we knew we wanted to create an app where users would need
                 to find hidden locations. Working within the constraints of our project guidelines, we decided
                 to incorporate Google Maps to build a scavenger hunt app that would take the user's current position
                 and tell them how far away they were from the scavenger hunt destination. We based this scavenger hunt
                 around buildings, statues, and popular places around UVA's Grounds, as we thought doing so would be a
                 fun and educational experience for people to get to know Grounds just a little bit more. </p>
                <h3>Learning Along the Way</h3>
                <p> While working on this project, we've learned more about the importance of being adaptable when
                    working on a team. We've also learned to not be scared of making mistakes, and instead embrace
                    a learning opportunity that may begin in failure. A lot of work required for this project was
                    uncharted terrority for our team, so we put a lot of effort into finding resources that would help
                    us figure out the right ways to implement our desired features. We discovered a lot not only
                    about software development, coding practices, and team building, but also about cool locations
                    on Grounds! We hope you can learn something new, too!</p>

            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

</body>

</html>

templates/CavQuest_app/add.html
<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'CavQuest_app/addHunt.css' %}">
    <link rel="stylesheet" href="{% static 'CavQuest_app/navbar.css' %}">
</head>
<body>
<ul class="menu">
  <li><a class="active" href="{% url 'homepage_loggedin' %}">Home</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:user_profile' %}"> Profile</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:tutorial' %}"> Tutorial</a></li>
  <li><a class="active" href="{% url 'CavQuest_app:logout_view' %}"> Logout</a></li>
</ul>
<div class="bg-img" >
<div class="full-page-container">
    <div class="content-container">
    <h1>Add Name, Hints, and Description</h1>
    <p class="add_desc">Submit a scavenger hunt name, three hints,  a little description of the thing that a searcher would need to find, and level of difficulty </p>
    <div class="container">
        <form method="post" class="submission-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_submission_form.as_p }}
            <div class="button-container">
                <button type="submit" class="submission-button"><span> SUBMIT! </span></button>
                <!--<a href="{% url 'CavQuest_app:homepage_loggedin' %}" class="GFG uniform-button" style="text-decoration: none;">Back</a> -->
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</body>
</html>

templates/CavQuest_app/admin_profile.html
<html lang="en">
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'CavQuest_app/user_profile.css' %}">
<head>
    <title>Admin Profile</title>
</head>
<body>
<ul class="menu">
    <li><a class="active" href="{% url 'homepage_loggedin' %}">Home</a></li>
    <li><a class="active" href="{% url 'CavQuest_app:user_profile' %}"> Profile</a></li>
    <li><a class="active" href="{% url 'CavQuest_app:tutorial' %}"> Tutorial</a></li>
    <li><a class="active" href="{% url 'CavQuest_app:about' %}"> About</a></li>

    <li><a class="active" href="{% url 'CavQuest_app:logout_view' %}"> Logout</a></li>
</ul>
<h2>Admin Profile</h2>

<p>Welcome, Admin {{ user.get_full_name }}!</p>
<div class="profile-container">
    <div class="profile-header"></div>
    <img id="avatar-preview"
         src="{% if user.userprofile.profile_picture %}{{ user.userprofile.profile_picture.url }}{% else %}{% static 'images/default-avatar.png' %}{% endif %}"
         alt="User Avatar" class="user-avatar">
    <div class="user-information">
        <h4><b>{{ user.username }}</b></h4>
        <p>{{ user.email }}</p>
    </div>
    <button id="edit-profile-button" class="btn btn-primary">Edit Profile</button>
    <div id="edit-profile-modal" class="modal">

        <div class="modal-content">
            <span class="close">&times;</span>
            <form id="edit-profile-form" method="post" action="{% url 'CavQuest_app:change_username' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="new_username" class="form-label">Change your username</label>
                    <input type="text" class="form-control" id="new_username" name="new_username"
                           placeholder="Enter new username">
                </div>
                <div class="mb-3">
                    <label for="profile_picture" class="form-label">Upload Profile Picture</label>
                    <input type="file" class="form-control" id="profile_picture" name="profile_picture"
                           onchange="previewFile()">
                </div>
                <button type="submit" class="btn btn-outline-secondary">Save Changes</button>
            </form>
        </div>

    </div>
</div>


<script>
        document.getElementById('edit-profile-form').addEventListener('submit', function(event) {
            event.preventDefault();

            var formData = new FormData(this);
            fetch('{% url "CavQuest_app:change_username" %}', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.username_taken) {
                    alert('Username already taken.');
                } else {
                    modal.style.display = "none";
                    window.location.reload();
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });
        var modal = document.getElementById("edit-profile-modal");

        var btn = document.getElementById("edit-profile-button");

        var span = document.getElementsByClassName("close")[0];

        btn.onclick = function() {
          modal.style.display = "block";
        }

        span.onclick = function() {
          modal.style.display = "none";
        }

        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
        function previewFile() {
          var preview = document.getElementById('avatar-preview'); // Selects the image
          var file    = document.getElementById('profile_picture').files[0]; // Selects the input
          var reader  = new FileReader();

          reader.onloadend = function () {
            preview.src = reader.result;
          }

          if (file) {
            reader.readAsDataURL(file);
          } else {
            preview.src = "{% static 'images/default-avatar.png' %}";
          }
       }

</script>

</body>
</html>

templates/CavQuest_app/congratulations.html
<!DOCTYPE html>
<html>
<head>
    <title>Congratulations!</title>
    {% load static %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'CavQuest_app/navbar.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: #dce4eb;
            text-align: center;
            font-family: 'Montserrat', sans-serif;
        }
        h1 {
            color: #4CAF50;
            font-size: 3rem;
            margin-bottom: 10px;
        }
        p {
            font-size: 1.5rem;
            margin-bottom: 30px;
        }
        .image-container {
            width: 200px;
            height: 200px;
            margin: 0 auto 20px;
            border: 2px solid #4CAF50;
            box-sizing: border-box;
            overflow: hidden;
        }
        .image-container img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .GFG {
            background-color: white;
            border: 2px solid #4CAF50;
            color: green;
            padding: 15px 30px;
            text-align: center;
            display: inline-block;
            font-size: 20px;
            margin: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }
        .GFG:hover {
            background-color: #4CAF50;
            color: white;
            transform: translateY(-3px);
            box-shadow: 0 10px 20px rgba(0,0,0,0.2);
        }
        @media (max-width: 768px) {
            h1 {
                font-size: 2.5rem;
            }
            p {
                font-size: 1.2rem;
            }
        }
    </style>
</head>
<body>
    <ul class="menu">
        <li><a class="active" href="{% url 'homepage_loggedin' %}">Home</a></li>
        <li><a class="active" href="{% url 'CavQuest_app:user_profile' %}">Profile</a></li>
        <li><a class="active" href="{% url 'CavQuest_app:tutorial' %}">Tutorial</a></li>
        <li><a class="active" href="{% url 'CavQuest_app:logout_view' %}">Logout</a></li>
    </ul>
    <h1>Congratulations!</h1>
    <p>You have completed the scavenger hunt!</p>
    <div class="image-container">
        {% if place.image %}
            <img src="{{ place.image.url }}" alt="Place Image">
        {% else %}
            <p>No image available for this task.</p>
        {% endif %}
    </div>
    <a href="{% url 'CavQuest_app:task_list' %}">
        <button class="GFG">Back to Scavenger Hunts</button>
    </a>
</body>
</html>


templates/index.html
{% load socialaccount %}
<html>
<body>
<h1>CavQuest </h1>
{% if user.is_authenticated %}
  <p>Welcome, You are logged in as {{ user.username }} ({{ user.email }})</p>
  <a href="{% url 'logout' %}">Logout</a>
  <a href="{% url 'add_tasks' %}">Add tasks</a>
{% else %}
  <a href="{% provider_login_url 'google' %}">Login With Google</a>
{% endif %}
</body>
</html>